# Generated by Django 5.2.1 on 2025-09-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='in_progress', max_length=100),
        ),
    ]
