from django.urls import path, include
from .views import OfferViewSet, OfferDetailListView, OffersDetailsSingleView, OfferOfBusinessUserView
from rest_framework import routers

"""
URL configuration for the offers application.

This module defines all API endpoints related to offers, offer details,
and business user offers. It uses Django REST Framework's router
for automatic ViewSet registration and explicit path definitions
for class-based views.

Routes:
    /offers/ (list, create)
    /offers/<pk>/ (retrieve, update, delete)
    /<business_user_id>/ (list offers of a specific business user)
    /offerdetails/ (list, create offer details)
    /offerdetails/<pk>/ (retrieve, update, delete single offer detail)
"""

router = routers.SimpleRouter()
router.register(r'offers', OfferViewSet, basename='offer')

urlpatterns = [
    # Includes routes automatically generated by the DRF router
    path('', include(router.urls)),

    # Custom endpoint to retrieve offers of a specific business user
    path(
        '<int:business_user_id>/',
        OfferOfBusinessUserView.as_view(),
        name="offer_business_user"
    ),

    # Endpoint for listing and creating offer details
    path(
        'offerdetails/',
        OfferDetailListView.as_view(),
        name="offerdetails-list"
    ),

    # Endpoint for retrieving, updating, or deleting a single offer detail
    path(
        'offerdetails/<int:pk>/',
        OffersDetailsSingleView.as_view(),
        name="offerdetails-detail"
    )
]
