# Generated by Django 5.2.1 on 2025-06-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='offer',
            new_name='offer_details',
        ),
    ]
