# Generated by Django 5.2.1 on 2025-06-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_alter_offer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='image',
        ),
        migrations.AddField(
            model_name='offer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
