# Generated by Django 5.2.1 on 2025-06-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0005_alter_offer_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetails',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='offer-details-images/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='offer-images/'),
        ),
    ]
