# Generated by Django 5.2.1 on 2025-06-30 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0006_offerdetails_file_alter_offer_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdetails',
            name='file',
        ),
    ]
