# Generated by Django 5.2.1 on 2025-06-03 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(blank=True)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('tel', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('working_hours', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('customer', 'Customer'), ('business', 'Business')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
